version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/usr/src/app/data/db.sqlite3
      - CRET_KEY=${CRET_KEY}
    depends_on:
      - db

  db:
    image: "alpine"
    volumes:
      - sqlite-data:/usr/src/app/data
    environment:
      - DATABASE_URL=/usr/src/app/data/db.sqlite3

volumes:
  sqlite-data:
